-- DROP TABLE IF EXISTS aanestys CASCADE; -- Muista IF EXISTS ja CASCADE parametrit!
-- DROP TABLE IF EXISTS aani CASCADE;
-- DROP TABLE IF EXISTS ehdokas CASCADE;
-- DROP TABLE IF EXISTS kayttaja CASCADE;






DROP TABLE IF EXISTS Aanestys CASCADE; -- Muista IF EXISTS ja CASCADE parametrit!
DROP TABLE IF EXISTS Kayttaja CASCADE;
DROP TABLE IF EXISTS Ehdokas CASCADE;
DROP TABLE IF EXISTS Aanet CASCADE;
DROP TABLE IF EXISTS Aanestaneet CASCADE;